# Funding & Sponsorship for Sentinel
# Built by Glincker (A GLINR Product)

github: glincker
patreon: gdsks
open_collective: sentinel
custom:
  - "https://glincker.com/sponsor"
  - "https://buymeacoffee.com/gdsks"
