blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/GLINCKER/sentinel/discussions/new?category=q-a
    about: Ask questions and discuss with the community
  - name: 💡 General Discussion
    url: https://github.com/GLINCKER/sentinel/discussions/new?category=general
    about: Discuss ideas, share feedback, or chat about Sentinel
  - name: 📖 Documentation
    url: https://github.com/GLINCKER/sentinel#documentation
    about: Read the documentation for guides and API reference
